name: Creating Release


on:
  push:
    tags:
      - 'v*'


jobs:
    build_release:
      name: Create Release
      permissions:
        contents: write
        issues: write
        pull-requests: write
      runs-on: ubuntu-latest
      environment: prod

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Create Release
          id: create_release
          #uses: actions/create-release@v1
          uses: ncipollo/release-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag: ${{ github.ref }}
            name: Release ${{ github.ref }}
            draft: false
            prerelease: false
