name: Creating Release


on:
  push:
    tags:
      - 'v*'


jobs:
    build_release:
      name: Create Release
      permissions:
        contents: write
        issues: write
        pull-requests: write
      runs-on: ubuntu-latest
      environment: staging

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Get tag name
          id: tag_name
          run: |
            version_number=$(git describe --tags `git rev-list --tags --max-count=1`)
            version_number=$(echo $version_number | tr -d ' ')
            version_number="${version_number:1}"
            echo "tag-version=v${version_number}" >> $GITHUB_OUTPUT

        - name: Create Release
          id: create_release
          uses: ncipollo/release-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUB_SECRET }}
          with:
            name: Release ${{ steps.tag_name.outputs.tag-version }}
