name: Workflow on Release


on:
  workflow_run:
    workflows: [Creating Release]
    types:
      - completed


jobs:
    publish_updated_job:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      permissions:
        contents: write
        issues: write
        pull-requests: write
        deployments: write
        actions: write
      environment:
        name: prod
      env:
      # DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_WORKSPACE }}

      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: pip install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pynacl

      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0

      - name: Extract branch name
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        id: extract_branch

      # Deploy code to the staging environment
      - name: Deploying
        run: |
          echo "Deploying code to production..."

      # Connect to azure
      - uses: Azure/login@v1
        name: Login to Azure
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      # Set databricks token as environmental variable
      - name: Generate databricks token
        id: generate-token
        run: |
          echo "DATABRICKS_TOKEN=$(az account get-access-token \
            --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | jq .accessToken -r)" >> $GITHUB_ENV

      # Pause previous prod job
      - name: Pause previous prod job
        env:
          JOB_ID_SECRET: ${{ secrets.JOB_ID_ACTIVE_PROD_JOB }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_WORKSPACE }}
        # DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        if: ${{ env.JOB_ID_SECRET != '' }}
        run: python $GITHUB_WORKSPACE/jobs/job_pause.py ${{ secrets.JOB_ID_ACTIVE_PROD_JOB }}

      # Pause previous prod job
      - name: Pause previous feature refresh prod job
        env:
          JOB_ID_SECRET: ${{ secrets.FEATURE_REFRESH_JOB_ID }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_WORKSPACE }}
        # DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        if: ${{ env.JOB_ID_SECRET != '' }}
        run: python $GITHUB_WORKSPACE/jobs/job_pause.py ${{ secrets.FEATURE_REFRESH_JOB_ID }}

      - name: Get tag name
        id: tag_name
        run: |
          version_number=$(git describe --tags `git rev-list --tags --max-count=1`)
          version_number=$(echo $version_number | tr -d ' ')
          version_number="${version_number:1}"
          echo "version-number=${version_number}" >> $GITHUB_OUTPUT
          echo "tag-version=v${version_number}" >> $GITHUB_OUTPUT

      # Get release date
      - name: Date
        id: release_date
        run: |
          printf -v date '%(%Y-%m-%d)T' -1
          echo "release-date=${date}" >> $GITHUB_OUTPUT

      # Deploy code to Prod workspace
      - name: Deploy Code
        run: |
          databricks workspace import_dir -o $GITHUB_WORKSPACE /Prod/Release-${{ steps.tag_name.outputs.tag-version }}/${{ steps.release_date.outputs.release-date }}

      # Create dist
      - name: Create whl
        env:
          VERSION: ${{ steps.tag_name.outputs.version-number }}
          BUILD_TAG: "alpha"
        run: |
          python setup.py bdist_wheel

      # Deploy code to Prod workspace
      - name: Deploy dist
        run: |
          databricks workspace import_dir -o $GITHUB_WORKSPACE/dist /Prod/Release-${{ steps.tag_name.outputs.tag-version }}/${{ steps.release_date.outputs.release-date }}/dist

      # Set git_sha as environmental variable in production job
      - name: Set GIT_SHA
        run: echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      # Update cluster conf
      - name: Update cluster conf
        run: |
          json=$(cat $GITHUB_WORKSPACE/jobs/cluster_conf.json)
          json=$(echo $json | jq -r ".spark_env_vars.GIT_SHA = \"${{ env.GIT_SHA }}\"")
          json=$(echo $json | jq -r ".cluster_id = \"${{ secrets.DATABRICKS_PROD_CLUSTER_ID }}\"")
          databricks clusters edit --json "$json"

      # Deploy code to the prod environment
      - name: Deploy to Production
        id: deploy_job
        run: |
          json=$(cat $GITHUB_WORKSPACE/jobs/pipeline_job.json)
          json=$(echo $json | jq -r ".git_source.git_tag = \"${{ steps.tag_name.outputs.tag-version }}\"")
          json=$(echo $json | jq -r ".name = \"PROD-pipeline-${{ steps.tag_name.outputs.tag-version }}\"")
          json=$(echo $json | jq -r ".schedule.quartz_cron_expression = \"36 26 10 * * ?\"")
          echo "$json"
          JOB_ID=$(databricks jobs create --json "$json" | jq -r '.job_id')
          echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT

      # Deploy code to the prod environment
      - name: Deploy monitoring job
        id: deploy_monitoring_job
        run: |
          json=$(cat $GITHUB_WORKSPACE/jobs/monitoring_job.json)
          json=$(echo $json | jq -r ".git_source.git_tag = \"${{ steps.tag_name.outputs.tag-version }}\"")
          json=$(echo $json | jq -r ".name = \"PROD-monitoring-${{ steps.tag_name.outputs.tag-version }}\"")
          echo "$json"
          JOB_ID=$(databricks jobs create --json "$json" | jq -r '.job_id')
          echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT

      # Deploy code to the prod environment
      - name: Deploy monitoring data job
        id: deploy_monitoring_data_job
        run: |
          json=$(cat $GITHUB_WORKSPACE/jobs/monitoring_job.json)
          json=$(echo $json | jq -r ".git_source.git_tag = \"${{ steps.tag_name.outputs.tag-version }}\"")
          json=$(echo $json | jq -r ".name = \"PROD-monitoring-data-${{ steps.tag_name.outputs.tag-version }}\"")
          echo "$json"
          JOB_ID=$(databricks jobs create --json "$json" | jq -r '.job_id')
          echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT

      # Deploy code to the prod environment
      # - name: Deploy features refresh
      #  id: deploy_frefresh_job
      #  run: |
      #    json=$(cat $GITHUB_WORKSPACE/jobs/features_refresh_job.json)
      #    json=$(echo $json | jq -r ".git_source.git_tag = \"${{ steps.tag_name.outputs.tag-version }}\"")
      #    json=$(echo $json | jq -r ".name = \"PROD-features-refresh-${{ steps.tag_name.outputs.tag-version }}\"")
      #    json=$(echo $json | jq -r ".schedule.quartz_cron_expression = \"36 26 8 * * ?\"")
      #    echo "$json"
      #    JOB_ID=$(databricks jobs create --json "$json" | jq -r '.job_id')
      #    echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT

      # Set new secret for prod pipeline id
      - name: Set job_id secret
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_SECRET }}
        run: python $GITHUB_WORKSPACE/jobs/set_secret.py ${{ steps.deploy_job.outputs.job_id }} JOB_ID_ACTIVE_PROD_JOB

      # Set new secret for prod monitoring id
      - name: Set monitoring job_id secret
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_SECRET }}
        run: python $GITHUB_WORKSPACE/jobs/set_secret.py ${{ steps.deploy_monitoring_job.outputs.job_id }} MONITORING_JOB_ID

      # Set new secret for prod monitoring id
      - name: Set monitoring data job_id secret
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_SECRET }}
        run: python $GITHUB_WORKSPACE/jobs/set_secret.py ${{ steps.deploy_monitoring_data_job.outputs.job_id }} MONITORING_DATA_JOB_ID

      # Set new secret for feature refresh job
      # - name: Set feature refresh job_id secret
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.MY_GITHUB_SECRET }}
      #  run: python $GITHUB_WORKSPACE/jobs/set_secret.py ${{ steps.deploy_frefresh_job.outputs.job_id }} FEATURE_REFRESH_JOB_ID

      # Delete recently created release branch
      - name: Delete release branch
        run: git push origin -d release/${{ steps.tag_name.outputs.tag-version }}
