name: Roll Back Current Production Model


on:
  workflow_dispatch:


jobs:
    roll_back:
      name: Roll Back
      permissions:
        contents: write
        issues: write
        pull-requests: write
        deployments: write
        actions: write
      runs-on: ubuntu-latest
      environment: prod
      env:
        MODEL_REGISTRY_TOKEN: ${{ secrets.DATABRICKS_MODEL_REGISTRY_TOKEN }}
        PROD_ENV_HOST: ${{ secrets.DATABRICKS_WORKSPACE }}
      # PROD_ENV_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        MODEL_REGISTRY_HOST: ${{ secrets.DATABRICKS_MODEL_REGISTRY_WORKSPACE }}

      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: install libraries
        run: python -m pip install requests

      # Connect to azure
      - uses: Azure/login@v1
        name: Login to Azure
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      # Set databricks token as environmental variable
      - name: Generate databricks token
        id: generate-token
        run: |
          echo "PROD_ENV_TOKEN=$(az account get-access-token \
            --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | jq .accessToken -r)" >> $GITHUB_ENV

      - name: get model name
        id: get_model_name
        run: |
          model_name=$(cat $GITHUB_WORKSPACE/jobs/current_model.json | jq -r '.current_model_name')
          echo "model-name=${model_name}" >> $GITHUB_OUTPUT

      # Delete bad production model deployed and re-productionize previous model that works
      # in a production environment
      - name: run roll back script
        run: python $GITHUB_WORKSPACE/jobs/roll_back.py ${{ steps.get_model_name.outputs.model-name }}

      # Possibly re-deploy production code of previous version
